# Generated by Django 5.2.15 on 2026-10-08 23:00

import json

from django.db import migrations, models


def archive_duplicate_exceptions(apps, schema_editor):
    """Identical grants are redundant; retain every row and its rollback metadata."""
    alias = schema_editor.connection.alias
    Exception = apps.get_model("db", "UserPermissionException")
    Log = apps.get_model("db", "APIActivityLog")
    fields = ("workspace_id", "user_id", "permission_id", "effect", "starts_at", "ends_at")
    duplicates = list(
        Exception.objects.using(alias)
        .filter(is_active=True, deleted_at__isnull=True)
        .values(*fields)
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for group in duplicates:
        selection = {field: group[field] for field in fields}
        rows = list(
            Exception.objects.using(alias)
            .filter(**selection, is_active=True, deleted_at__isnull=True)
            .order_by("created_at", "id")
        )
        for row in rows[1:]:
            Log.objects.using(alias).get_or_create(
                token_identifier=f"crm-migration:0130:Exception:{row.pk}",
                defaults={
                    "path": "/crm/migrations/0130/",
                    "method": "MIGRATE",
                    "response_code": 200,
                    "body": json.dumps({"id": str(row.pk), "is_active": True}),
                },
            )
            Exception.objects.using(alias).filter(pk=row.pk).update(is_active=False)


def restore_duplicate_exceptions(apps, schema_editor):
    alias = schema_editor.connection.alias
    Exception = apps.get_model("db", "UserPermissionException")
    for log in (
        apps.get_model("db", "APIActivityLog")
        .objects.using(alias)
        .filter(token_identifier__startswith="crm-migration:0130:Exception:")
        .iterator()
    ):
        saved = json.loads(log.body)
        Exception.objects.using(alias).filter(pk=saved["id"]).update(is_active=saved["is_active"])


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0129_crm_access_data"),
    ]

    operations = [
        migrations.RunPython(archive_duplicate_exceptions, restore_duplicate_exceptions),
        migrations.AddConstraint(
            model_name="userpermissionexception",
            constraint=models.CheckConstraint(
                condition=models.Q(("effect__in", ["ALLOW", "DENY"])), name="org_exception_valid_effect"
            ),
        ),
        migrations.AddConstraint(
            model_name="userpermissionexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("ends_at__isnull", True),
                    ("is_active", True),
                    ("starts_at__isnull", True),
                ),
                fields=("workspace", "user", "permission", "effect"),
                name="org_exception_unique_unbounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpermissionexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("ends_at__isnull", True),
                    ("is_active", True),
                    ("starts_at__isnull", False),
                ),
                fields=("workspace", "user", "permission", "effect", "starts_at"),
                name="org_exception_unique_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpermissionexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("ends_at__isnull", False),
                    ("is_active", True),
                    ("starts_at__isnull", True),
                ),
                fields=("workspace", "user", "permission", "effect", "ends_at"),
                name="org_exception_unique_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpermissionexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("ends_at__isnull", False),
                    ("is_active", True),
                    ("starts_at__isnull", False),
                ),
                fields=("workspace", "user", "permission", "effect", "starts_at", "ends_at"),
                name="org_exception_unique_bounded",
            ),
        ),
    ]
