param()
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$brandingRepoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$brandingAssets = Join-Path $brandingRepoRoot 'assets/branding'
$brandingUtf8 = [System.Text.UTF8Encoding]::new($false)

function Write-BrandImage([string]$Source, [string]$Target, [int]$Width, [int]$Height, [double]$Padding = 0) {
    $sourceImage = [System.Drawing.Bitmap]::new($Source)
    $targetImage = [System.Drawing.Bitmap]::new($Width, $Height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $graphics = [System.Drawing.Graphics]::FromImage($targetImage)
    try {
        $graphics.Clear([System.Drawing.Color]::Transparent)
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
        $graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $scale = [Math]::Min(($Width * (1 - 2 * $Padding)) / $sourceImage.Width, ($Height * (1 - 2 * $Padding)) / $sourceImage.Height)
        $imageWidth = $sourceImage.Width * $scale
        $imageHeight = $sourceImage.Height * $scale
        $destination = [System.Drawing.RectangleF]::new(($Width - $imageWidth) / 2, ($Height - $imageHeight) / 2, $imageWidth, $imageHeight)
        $graphics.DrawImage($sourceImage, $destination)
        $null = New-Item -ItemType Directory -Path (Split-Path -Parent $Target) -Force
        $targetImage.Save($Target, [System.Drawing.Imaging.ImageFormat]::Png)
    } finally {
        $graphics.Dispose()
        $targetImage.Dispose()
        $sourceImage.Dispose()
    }
}

function Write-BrandIco([string]$Target) {
    $images = @(16, 32, 48, 256) | ForEach-Object {
        $temporaryPng = Join-Path $brandingAssets "icon-$_.png"
        Write-BrandImage (Join-Path $brandingAssets 'amard-symbol.png') $temporaryPng $_ $_ 0.04
        [PSCustomObject]@{Size=$_;Bytes=[System.IO.File]::ReadAllBytes($temporaryPng)}
    }
    $stream = [System.IO.MemoryStream]::new()
    $writer = [System.IO.BinaryWriter]::new($stream)
    try {
        $writer.Write([UInt16]0)
        $writer.Write([UInt16]1)
        $writer.Write([UInt16]$images.Count)
        $offset = 6 + 16 * $images.Count
        foreach ($entry in $images) {
            $iconDimension = if ($entry.Size -eq 256) { 0 } else { $entry.Size }
            $writer.Write([byte]$iconDimension)
            $writer.Write([byte]$iconDimension)
            $writer.Write([byte]0)
            $writer.Write([byte]0)
            $writer.Write([UInt16]1)
            $writer.Write([UInt16]32)
            $writer.Write([UInt32]$entry.Bytes.Length)
            $writer.Write([UInt32]$offset)
            $offset += $entry.Bytes.Length
        }
        foreach ($entry in $images) { $writer.Write([byte[]]$entry.Bytes) }
        [System.IO.File]::WriteAllBytes($Target, $stream.ToArray())
    } finally { $writer.Dispose(); $stream.Dispose() }
}

$symbolMaster = Join-Path $brandingAssets 'amard-symbol.png'
$logoMaster = Join-Path $brandingAssets 'amard-logo.png'
Write-BrandImage $symbolMaster (Join-Path $brandingAssets 'amard-symbol-ui.png') 256 171
Write-BrandImage $logoMaster (Join-Path $brandingAssets 'amard-logo-ui.png') 384 256
$symbolData = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes((Join-Path $brandingAssets 'amard-symbol-ui.png')))
$logoData = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes((Join-Path $brandingAssets 'amard-logo-ui.png')))
$symbolSvg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 171"><image href="data:image/png;base64,' + $symbolData + '" width="256" height="171"/></svg>'
foreach ($svgAsset in @('apps/space/app/assets/plane-logo.svg', 'apps/admin/app/assets/logos/takeoff-icon-dark.svg', 'apps/admin/app/assets/logos/takeoff-icon-light.svg')) {
    [System.IO.File]::WriteAllText((Join-Path $brandingRepoRoot $svgAsset), $symbolSvg + "`n", $brandingUtf8)
}
$brandingVersion = (Get-FileHash -LiteralPath $symbolMaster -Algorithm SHA256).Hash.Substring(0,12).ToLowerInvariant()
$companyLogoAlt = [Regex]::Unescape('\u0644\u0648\u06af\u0648\u06cc\u0020\u062a\u062d\u0644\u06cc\u0644\u06af\u0631\u0627\u0646\u0020\u0622\u0645\u0627\u0631\u062f')
$brandingCode = @"
// Generated by assets/branding/prepare-branding.ps1. Do not edit image data manually.
export const COMPANY_LOGO_ALT = "$companyLogoAlt";
export const COMPANY_BRAND_VERSION = "$brandingVersion";
export const COMPANY_LOGO_SYMBOL: string = "data:image/png;base64,$symbolData";
export const COMPANY_LOGO_FULL: string = "data:image/png;base64,$logoData";
"@
[System.IO.File]::WriteAllText((Join-Path $brandingRepoRoot 'packages/constants/src/branding.ts'), $brandingCode + "`n", $brandingUtf8)

foreach ($application in @('web', 'admin', 'space')) {
    $appRoot = Join-Path $brandingRepoRoot "apps/$application"
    $faviconAssets = Join-Path $appRoot 'app/assets/favicon'
    $publicBranding = Join-Path $appRoot 'public/branding'
    $null = New-Item -ItemType Directory -Path $publicBranding -Force
    Copy-Item -LiteralPath (Join-Path $brandingAssets 'amard-logo-ui.png') -Destination (Join-Path $publicBranding 'amard-logo.png')
    Copy-Item -LiteralPath (Join-Path $brandingAssets 'amard-symbol-ui.png') -Destination (Join-Path $publicBranding 'amard-symbol.png')
    foreach ($dimension in @(16, 32, 180, 192, 512)) {
        Write-BrandImage $symbolMaster (Join-Path $publicBranding "amard-icon-$dimension.png") $dimension $dimension 0.08
    }
    foreach ($dimension in @(16, 32)) {
        Copy-Item -LiteralPath (Join-Path $publicBranding "amard-icon-$dimension.png") -Destination (Join-Path $faviconAssets "favicon-${dimension}x$dimension.png")
    }
    Copy-Item -LiteralPath (Join-Path $publicBranding 'amard-icon-180.png') -Destination (Join-Path $faviconAssets 'apple-touch-icon.png')
    Write-BrandIco (Join-Path $faviconAssets 'favicon.ico')
    Copy-Item -LiteralPath (Join-Path $faviconAssets 'favicon.ico') -Destination (Join-Path $appRoot 'public/favicon.ico')
    foreach ($dimension in @(192, 512)) {
        Copy-Item -LiteralPath (Join-Path $publicBranding "amard-icon-$dimension.png") -Destination (Join-Path $faviconAssets "android-chrome-${dimension}x$dimension.png")
    }
    if ($application -eq 'web') {
        foreach ($dimension in @(192, 512)) {
            Copy-Item -LiteralPath (Join-Path $publicBranding "amard-icon-$dimension.png") -Destination (Join-Path $appRoot "public/favicon/android-chrome-${dimension}x$dimension.png")
        }
    }
}

foreach ($dimension in @(180, 512)) {
    Write-BrandImage $symbolMaster (Join-Path $brandingRepoRoot "apps/web/app/assets/icons/icon-${dimension}x$dimension.png") $dimension $dimension 0.08
}
foreach ($dimension in @(192, 348, 512)) {
    Write-BrandImage $symbolMaster (Join-Path $brandingRepoRoot "apps/web/public/icons/icon-${dimension}x$dimension.png") $dimension $dimension 0.08
}
foreach ($application in @('web', 'space')) {
    foreach ($style in @('white', 'black')) {
        Write-BrandImage $logoMaster (Join-Path $brandingRepoRoot "apps/$application/app/assets/plane-logos/$style-horizontal-with-blue-logo.png") 384 256
    }
}
Write-Host "Brand assets prepared for web, admin and space; version $brandingVersion"
